--1 - Criar 2 Inserts
DESC TB_CLIENTE

INSERT INTO TB_CLIENTE (ID_CLIENTE, NOME, EMAIL, SEXO, TELEFONE, DATA_NASC, GRAU_INSTRUCAO, ESTADO, MUNICIPIO, BAIRRO)
     VALUES (500, 'MAURICIO DE SOUSA','MAURICIO@HOTMAIL.COM', 'M', 435345345, '24/05/1990', 'MESTRADO', 'SP', 'RIO PRETO','SÃO JOAQUIM');
     
     
INSERT INTO TB_CLIENTE (ID_CLIENTE, NOME, EMAIL, SEXO, TELEFONE, DATA_NASC, GRAU_INSTRUCAO, ESTADO, MUNICIPIO, BAIRRO)
     VALUES (400, 'MARIA DE SOUSA','MARIA@HOTMAIL.COM', 'F', 31232132, '11/05/1980', 'MÉDIO', 'SP', 'SÃO PAULO','SÉ');

SELECT * FROM TB_CLIENTE;



-- 2 - Criar 2 Updates
UPDATE TB_CLIENTE
     SET TB_CLIENTE.TELEFONE = 435345345 ,TB_CLIENTE.GRAU_INSTRUCAO = 'COMPLETO'
     WHERE TB_CLIENTE.ID_CLIENTE  = 400; 
     
UPDATE TB_CLIENTE
     SET TB_CLIENTE.EMAIL ='M.SOUZA@GMAIL.COM' ,TB_CLIENTE.NOME = 'MAURICIO DE SOUZA'
     WHERE TB_CLIENTE.ID_CLIENTE  = 500;    
     
SELECT * FROM TB_CLIENTE;



--3 - Criar 2 Deletes
DELETE FROM TB_CLIENTE
WHERE TB_CLIENTE.ID_CLIENTE  = 500;

DELETE FROM TB_CLIENTE
WHERE TB_CLIENTE.ID_CLIENTE  = 400;

SELECT * FROM TB_CLIENTE;


-- 4 - Criar 3 selects simples ( seleção com filtros )

-- SELECIONE TODOS OS CLIENTES DE SEXO FEMININO COM SEUS TELEFONES 
SELECT * FROM TB_CLIENTE;

SELECT TB_CLIENTE.NOME, TB_CLIENTE.SEXO, TB_CLIENTE.TELEFONE
FROM TB_CLIENTE
WHERE TB_CLIENTE.SEXO = 'F';


--SELECIONE TODOS OS PRODDUTOS QUE TENHAM VALORES MAIORES QUE 3,O0 REAIS
SELECT * FROM TB_PRODUTO;

SELECT TB_PRODUTO.ID_PRODUTO, TB_PRODUTO.DESCRICAO_PROD, PRECO_UNI
FROM TB_PRODUTO
WHERE TB_PRODUTO.PRECO_UNI > 3.00;


--SELECIONE TODOS OS VENDEDORES DE SÃO PAULO 
SELECT * FROM TB_VENDEDOR;

SELECT TB_VENDEDOR.ID_VENDEDOR, TB_VENDEDOR.NOME, TB_VENDEDOR.ESTADO
FROM TB_VENDEDOR
WHERE TB_VENDEDOR.ESTADO = 'SP';







--5 - Criar 3 selects com Joins ( 2 ou mais tabelas )

-- SELECIONTE TODAS AS VENDAS REALIZADAS POR CADA VENDEDOR
SELECT * FROM TB_VENDEDOR;
SELECT * FROM TB_VENDA;

SELECT TB_VENDEDOR.NOME, TB_VENDA.DATA_COMPRA, TB_VENDA.QTD_VENDIDA, TB_VENDA.COD_CARRINHO, TB_VENDA.VALOR_TOTAL
FROM TB_VENDEDOR, TB_VENDA
WHERE TB_VENDEDOR.ID_VENDEDOR = TB_VENDA.ID_VENDEDOR;

--SELECIONE TODOS OS PRODUTOS QUE FORAM VENDIDOS 
SELECT * FROM TB_PRODUTO;
SELECT * FROM TB_VENDA;

SELECT TB_PRODUTO.DESCRICAO_PROD, TB_VENDA.QTD_VENDIDA, TB_VENDA.COD_CARRINHO, TB_VENDA.VALOR_TOTAL
FROM TB_PRODUTO, TB_VENDA
WHERE TB_PRODUTO.ID_PRODUTO =  TB_VENDA.ID_PRODUTO;


-- SELECIONE QUAIS FORAM AS COMPRAS EFETUADAS DE CADA CLIENTE
SELECT * FROM TB_CLIENTE;
SELECT * FROM TB_VENDA;
SELECT * FROM TB_PRODUTO;

SELECT TB_CLIENTE.NOME, TB_PRODUTO.DESCRICAO_PROD, TB_PRODUTO.PRECO_UNI, TB_VENDA.DATA_COMPRA, TB_VENDA.COD_CARRINHO, TB_VENDA.VALOR_TOTAL
FROM TB_CLIENTE, TB_VENDA, TB_PRODUTO
WHERE TB_VENDA.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO
    AND  TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE;
    
    
    
    
  -- 6 - Criar 3 selects com agrupamentos   
  
  -- AGRUPAMENTO TOTAL DE VALOR DE VENDAR POR DIA 
SELECT * FROM TB_VENDA;

SELECT SUM(TB_VENDA.VALOR_TOTAL) AS "VALOR TOTAL" , (TB_VENDA.DATA_COMPRA) AS "MÊS" 
FROM TB_VENDA 
GROUP BY (TB_VENDA.DATA_COMPRA);

--- AGRUPAMENTO DO VALOR TOTAL FEITO POR TIPO DE CARRINHO, SEPARADAS POR DATAS 
SELECT  TB_VENDA.COD_CARRINHO AS "CARRINHO", SUM(TB_VENDA.VALOR_TOTAL) AS "VALOR TOTAL" , TB_VENDA.DATA_COMPRA AS "MÊS"
FROM TB_VENDA 
GROUP BY TB_VENDA.COD_CARRINHO, TB_VENDA.DATA_COMPRA;


-- FAÇA UMA CONTAGEM DE PESSOAS POR ESTADO E SEXO 
SELECT TB_CLIENTE.ESTADO, TB_CLIENTE.SEXO, COUNT(TB_CLIENTE.ESTADO) "TOTAL DE PESSOAS"
FROM TB_CLIENTE
GROUP BY TB_CLIENTE.ESTADO, TB_CLIENTE.SEXO;


--SELECIONE POR COLUNA QUANTOS HOMENS E QUANTAS MULHERES TEM EM CADA ESTADO 
SELECT DISTINCT TB_CLIENTE.ESTADO, VW_MULHERES.TOTAL_MULHERES, VW_HOMENS.TOTAL_HOMENS
FROM(
    SELECT TB_CLIENTE.ESTADO AS ESTADO_MULHERES, COUNT(TB_CLIENTE.ESTADO) AS TOTAL_MULHERES
    FROM TB_CLIENTE
    WHERE TB_CLIENTE.SEXO = 'F'
    GROUP BY TB_CLIENTE.ESTADO) VW_MULHERES,
    (SELECT TB_CLIENTE.ESTADO AS ESTADO_HOMENS,  COUNT(TB_CLIENTE.ESTADO) AS TOTAL_HOMENS
    FROM TB_CLIENTE
    WHERE TB_CLIENTE.SEXO = 'M'
    GROUP BY TB_CLIENTE.ESTADO) VW_HOMENS
    ,TB_CLIENTE
WHERE TB_CLIENTE.ESTADO = VW_MULHERES.ESTADO_MULHERES(+) AND TB_CLIENTE.ESTADO = VW_HOMENS.ESTADO_HOMENS(+);




--7 - Criar 3 selects com agrupamentos e joins
--8 - Criar 3 selects com agrupamentos/Joins e filtros

-- SELECIONE QUANTOS TIPOS DE PAGAMENTOS FORAM REALIZADOS EM CADA ESTADO (COM BASE NO ESTADO DO CLIENTE)
SELECT TB_CLIENTE.ESTADO AS "ESTADO DO CLIENTE", TB_PAGAMENTO.TIPO_PAGAMENTO AS "TIPO DE PAGAMENTO", COUNT(TB_PAGAMENTO.TIPO_PAGAMENTO) AS "TOTAL REALIZADO"
FROM TB_CLIENTE, TB_PAGAMENTO, TB_VENDA
WHERE TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
AND   TB_PAGAMENTO.ID_PAGAMENTO = TB_VENDA.ID_PAGAMENTO
GROUP BY TB_CLIENTE.ESTADO, TB_PAGAMENTO.TIPO_PAGAMENTO;


-- QUANTOS PRODUTOS O VENDEDOR VENDEU DE CADA FORNECEDOR 
SELECT TB_VENDEDOR.NOME AS "VENDEDORES", TB_FORNECEDOR.NOME AS "FORNECEDORES", COUNT( TB_FORNECEDOR.NOME) AS "TOTAL DE VENDAS"
FROM TB_VENDEDOR, TB_VENDA, TB_PRODUTO,TB_FORNECEDOR
WHERE TB_VENDEDOR.ID_VENDEDOR = TB_VENDA.ID_VENDEDOR
AND   TB_VENDA.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO
AND   TB_PRODUTO.ID_FORNECEDOR = TB_FORNECEDOR.ID_FORNECEDOR
GROUP BY TB_VENDEDOR.NOME, TB_FORNECEDOR.NOME
ORDER BY  TB_VENDEDOR.NOME


-- SELECIONE MÉDIA DE VALORES VENDIDO POR CATEGORIA 
SELECT TB_CATEGORIA.RAMO AS "CATEGORIA", ROUND(AVG(TB_VENDA.VALOR_TOTAL),2) AS "MÉDIA DE VENDAS"
FROM TB_VENDA, TB_PRODUTO,TB_CATEGORIA
WHERE TB_VENDA.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO
AND   TB_PRODUTO.ID_CATEGORIA = TB_CATEGORIA.ID_CATEGORIA
GROUP BY  TB_CATEGORIA.RAMO



-- SELECIONE MÉDIA DE VALORES VENDIDO POR CATEGORIA ONDE OS PAGAMENTOS FORAM FEITOS POR PIX
SELECT TB_CATEGORIA.RAMO AS "CATEGORIA", ROUND(AVG(TB_VENDA.VALOR_TOTAL),2) AS "MÉDIA DE VENDAS"
FROM TB_VENDA, TB_PRODUTO,TB_CATEGORIA, TB_PAGAMENTO
WHERE TB_VENDA.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO
AND   TB_VENDA.ID_PAGAMENTO = TB_PAGAMENTO.ID_PAGAMENTO
AND   TB_PRODUTO.ID_CATEGORIA = TB_CATEGORIA.ID_CATEGORIA
AND   TB_PAGAMENTO.TIPO_PAGAMENTO = 'PIX'
GROUP BY  TB_CATEGORIA.RAMO


SELECT * FROM TB_CLIENTE
SELECT TO_CHAR(DATA_NASC,'YYYY') FROM TB_CLIENTE

SELECT TO_CHAR('04/11/2000','YYYY') FROM DUAL

SELECT TO_NUMBER(TO_CHAR(TO_DATE('04/11/2000','DD/MM/YYYY'),'YYYY')) FROM DUAL



-- SELECIONAR TODOS OS PRODUTOS VENDIDOS E SEPARAR POR PERIODO ENTRE 1980 E 1995 A QUANTIDADE QUE CADA PRODUTO FOI VENDIDO EM CADA
SELECT TB_PRODUTO.DESCRICAO_PROD, TB_CLIENTE.DATA_NASC, COUNT(TB_PRODUTO.DESCRICAO_PROD)
FROM   TB_CLIENTE, TB_PRODUTO, TB_VENDA
WHERE  TO_NUMBER(TO_CHAR(TB_CLIENTE.DATA_NASC,'YYYY')) BETWEEN 1980 AND 1995
AND    TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
AND    TB_VENDA.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO
GROUP BY   TB_PRODUTO.DESCRICAO_PROD,  TB_CLIENTE.DATA_NASC
ORDER BY  TB_PRODUTO.DESCRICAO_PROD
