CREATE DATABASE BANCO;


USE BANCO;

CREATE TABLE TB_CLIENTE (
	ID_CLIENTE BIGINT NOT NULL PRIMARY KEY,
    NOME  VARCHAR(100) NOT NULL, 
    CPF  VARCHAR(100) NOT NULL, 
    RUA  VARCHAR(100) NOT NULL, 
    BAIRRO  VARCHAR(100) NOT NULL, 
    CIDADE  VARCHAR(100) NOT NULL, 
    ESTADO  VARCHAR(100) NOT NULL, 
    SEXO  VARCHAR(100) NOT NULL, 
    IDADE BIGINT NOT NULL
);


CREATE TABLE TB_TRANSACAO(
	ID_TRANSACAO  BIGINT NOT NULL PRIMARY KEY,
	PIX TINYINT(1) NOT NULL,
	DOC TINYINT(1) NOT NULL,
	TED TINYINT(1) NOT NULL
);

CREATE TABLE TB_FUNCIONARIO (
	ID_FUNCIONARIO BIGINT NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL, 
    CIDADE VARCHAR(100) NOT NULL
);

CREATE TABLE TB_LOCALIDADE(
	ID_LOCALIDADE BIGINT NOT NULL PRIMARY KEY,
    REGIAO VARCHAR(100) NOT NULL, 
    CIDADE VARCHAR(100) NOT NULL, 
    ESTADO VARCHAR(100) NOT NULL
);

CREATE TABLE TB_AGENCIA(
	ID_AGENCIA BIGINT NOT NULL PRIMARY KEY,
    N_AGENCIA BIGINT NOT NULL,
    NOME VARCHAR(100) NOT NULL, 
    ENDERECO  VARCHAR(100) NOT NULL, 
    FK_ID_LOCALIDADE  BIGINT NOT NULL,
    FOREIGN KEY (FK_ID_LOCALIDADE) REFERENCES  TB_LOCALIDADE(ID_LOCALIDADE)
);

CREATE TABLE TB_GERENTE(
	ID_GERENTE BIGINT NOT NULL PRIMARY KEY,
    CPA  TINYINT(1) NOT NULL,
    CPO  TINYINT(1) NOT NULL,
    SALARIO  REAL NOT NULL,
    FK_ID_AGENCIA  BIGINT NOT NULL,
    FK_ID_FUNCIONARIO  BIGINT NOT NULL,
    FOREIGN KEY (FK_ID_FUNCIONARIO) REFERENCES  TB_FUNCIONARIO(ID_FUNCIONARIO),
    FOREIGN KEY (FK_ID_AGENCIA) REFERENCES  TB_AGENCIA(ID_AGENCIA)
);


CREATE TABLE TB_CONTA(
	ID_CONTA  BIGINT NOT NULL PRIMARY KEY,
	N_CONTA VARCHAR(100) NOT NULL, 
	SALDO  REAL NOT NULL,
	POUPANCA TINYINT(1) NOT NULL,
	CONJUNTA TINYINT(1) NOT NULL,
	CORRENTE TINYINT(1) NOT NULL,
	FK_ID_AGENCIA  BIGINT NOT NULL,
	FK_ID_GERENTE  BIGINT NOT NULL,
	FOREIGN KEY (FK_ID_AGENCIA) REFERENCES  TB_AGENCIA(ID_AGENCIA),
    FOREIGN KEY (FK_ID_GERENTE) REFERENCES  TB_GERENTE(ID_GERENTE)
);

CREATE TABLE TB_CLIENTE_CONTA(
	ID_CLIENTE_CONTA BIGINT NOT NULL PRIMARY KEY,
	FK_ID_CLIENTE  BIGINT NOT NULL,
	FK_ID_CONTA  BIGINT NOT NULL,
	FOREIGN KEY (FK_ID_CLIENTE) REFERENCES  TB_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (FK_ID_CONTA) REFERENCES  TB_CONTA(ID_CONTA)
);

CREATE TABLE TB_CLIENTE_CONTA_TRANSACAO(
	ID_CLIENTE_CONTA_TRANSACAO  BIGINT NOT NULL PRIMARY KEY,
	DATA_REALIZADO DATE NOT NULL,
	SALDO_SAIDA REAL ,
	SALDO_ENTRADA REAL ,
	FK_ID_CLIENTE_CONTA BIGINT NOT NULL,
	FK_ID_TRANSACAO BIGINT NOT NULL,
	FOREIGN KEY (FK_ID_CLIENTE_CONTA) REFERENCES  TB_CLIENTE_CONTA(ID_CLIENTE_CONTA),
    FOREIGN KEY (FK_ID_TRANSACAO) REFERENCES  TB_TRANSACAO(ID_TRANSACAO)
);

  